export const SECRET = 'eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY3MDY2OTM2NCwiaWF0IjoxNjcwNjY5MzY0fQ.TahevmfnTAkIgrbkbJSJQo0CAgdaDzMAdGNOhqVSZMc';
export enum USER_TYPE {
    BUYER = 'BUYER',
    SELLER = 'SELLER'
}